name: ble_messege_converter
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  path: any
  collection: ^1.17.0
  crclib: ^3.0.0
  dart_frog: ^0.3.0
  # influxdb_client: ^2.2.0
  mime: ^1.0.4
  ffigen: ^4.1.3
  dio: ^5.1.0
  

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^4.0.0
